# Locate libuv library
# This module defines
#  LIBUV_FOUND, if false, do not try to link to libuv
#  LIBUV_LIBRARIES
#  LIBUV_INCLUDE_DIRS, where to find uv.h

FIND_PATH(LIBUV_INCLUDE_DIRS NAMES uv.h HINTS ${LIBUV_DIR}/include)
FIND_LIBRARY(LIBUV_LIBRARIES NAMES uv libuv HINTS ${LIBUV_DIR}/Debug/lib ${LIBUV_DIR}/lib ${LIBUV_DIR})

if(WIN32)
  list(APPEND LIBUV_LIBRARIES_WIN iphlpapi)
  list(APPEND LIBUV_LIBRARIES_WIN psapi)
  list(APPEND LIBUV_LIBRARIES_WIN userenv)
  list(APPEND LIBUV_LIBRARIES_WIN ws2_32)
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBUV DEFAULT_MSG LIBUV_LIBRARIES LIBUV_INCLUDE_DIRS)

if(LIBUV_FOUND AND NOT TARGET LIBUV)
  add_library(uv UNKNOWN IMPORTED)
  set_target_properties(uv PROPERTIES
	IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
	IMPORTED_LOCATION "${LIBUV_LIBRARIES}"
	INTERFACE_LINK_LIBRARIES "${LIBUV_LIBRARIES_WIN}"
	INTERFACE_INCLUDE_DIRECTORIES "${LIBUV_INCLUDE_DIRS}"
	)
endif()
