set(CPACK_PACKAGE_VENDOR "Darren Smith")
SET(CPACK_PACKAGE_CONTACT "Darren Smith")

set(CPACK_PACKAGING_INSTALL_PREFIX "/usr/lib")

SET(CPACK_GENERATOR "DEB")
SET(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS ON)

set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS YES)

set(CPACK_COMPONENTS_ALL lib dev)
set(CPACK_COMPONENT_DEV_DEPENDS lib)

set(CPACK_DEBIAN_LIB_PACKAGE_NAME libwampcc)
set(CPACK_DEBIAN_DEV_PACKAGE_NAME libwampcc-dev)

if(BUILD_UTILS)
  list(APPEND CPACK_COMPONENTS_ALL util)
  set(CPACK_COMPONENT_UTIL_DEPENDS lib)
  set(CPACK_DEBIAN_UTIL_PACKAGE_NAME wampcc-utils)
endif()

include(CPack)
